"""
ORM table definitions.
These are SQLAlchemy models — completely separate from the Pydantic models
in app/models.py which are the API response contracts.
"""

from datetime import datetime, timezone
from typing import Optional
from sqlalchemy import (
    Integer, String, Float, Boolean,
    DateTime, ForeignKey, Index, JSON,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship, backref

from app.db.engine import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


# ── users ─────────────────────────────────────────────────────────────────────

class User(Base):
    """Application user account."""
    __tablename__ = "users"

    id:         Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    email:      Mapped[str]      = mapped_column(String, nullable=False, unique=True)
    username:   Mapped[str]      = mapped_column(String, nullable=False, unique=True)
    hashed_pw:  Mapped[str]      = mapped_column(String, nullable=False)
    is_admin:   Mapped[bool]     = mapped_column(Boolean, nullable=False, default=False)
    is_active:  Mapped[bool]     = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    __table_args__ = (
        Index("ix_users_email", "email"),
        Index("ix_users_username", "username"),
    )

    def __repr__(self) -> str:
        return f"<User id={self.id} username={self.username!r}>"


class RefreshToken(Base):
    """Long-lived refresh tokens stored in DB for session management."""
    __tablename__ = "refresh_tokens"

    id:         Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id:    Mapped[int]      = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    token:      Mapped[str]      = mapped_column(String, nullable=False, unique=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    __table_args__ = (
        Index("ix_refresh_tokens_token", "token"),
    )


class InviteCode(Base):
    """One-time invite codes generated by admins for invite-only registration."""
    __tablename__ = "invite_codes"

    id:         Mapped[int]            = mapped_column(Integer, primary_key=True, autoincrement=True)
    code:       Mapped[str]            = mapped_column(String, nullable=False, unique=True)
    created_by: Mapped[int]            = mapped_column(Integer, ForeignKey("users.id"), nullable=False)
    used_by    = mapped_column(Integer, ForeignKey("users.id"), nullable=True)
    used_at    = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime]       = mapped_column(DateTime(timezone=True), default=_now)

    __table_args__ = (
        Index("ix_invite_codes_code", "code"),
    )


# ── holdings ─────────────────────────────────────────────────────────────────

class Holding(Base):
    """Active and historical positions. Source of truth for tickers."""
    __tablename__ = "holdings"

    id:         Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id:    Mapped[int]      = mapped_column(Integer, ForeignKey("users.id"), nullable=False, server_default="1")
    ticker:     Mapped[str]      = mapped_column(String,  nullable=False)
    name:       Mapped[str]      = mapped_column(String,  nullable=False)
    market:     Mapped[str]      = mapped_column(String,  nullable=False)   # 'ngx' | 'us'
    shares:     Mapped[float]    = mapped_column(Float,   nullable=False)
    avg_cost:   Mapped[float]    = mapped_column(Float,   nullable=False)
    sector:     Mapped[str]      = mapped_column(String,  nullable=False, default="")
    is_active:  Mapped[bool]     = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    __table_args__ = (
        Index("ix_holdings_market_active",       "market", "is_active"),
        Index("ix_holdings_ticker",              "ticker"),
        Index("ix_holdings_user_market_active",  "user_id", "market", "is_active"),
    )

    def to_dict(self) -> dict:
        return {
            "ticker":   self.ticker,
            "name":     self.name,
            "shares":   self.shares,
            "avg_cost": self.avg_cost,
            "sector":   self.sector,
        }


# ── closed_positions ──────────────────────────────────────────────────────────

class ClosedPosition(Base):
    """Immutable record of exited positions and their realised P&L."""
    __tablename__ = "closed_positions"

    id:          Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id:     Mapped[int]      = mapped_column(Integer, ForeignKey("users.id"), nullable=False, server_default="1")
    ticker:      Mapped[str]      = mapped_column(String,  nullable=False)
    name:        Mapped[str]      = mapped_column(String,  nullable=False)
    market:      Mapped[str]      = mapped_column(String,  nullable=False)   # 'ngx' | 'us'
    realized_pl: Mapped[float]    = mapped_column(Float,   nullable=False)   # local currency
    closed_at:   Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    __table_args__ = (
        Index("ix_closed_market",      "market"),
        Index("ix_closed_user_market", "user_id", "market"),
    )


# ── portfolio_snapshots ───────────────────────────────────────────────────────

class PortfolioSnapshot(Base):
    """
    One row written per /api/data call (rate-limited by NGX_PRICE_TTL).
    Backbone of all historical charts.
    """
    __tablename__ = "portfolio_snapshots"

    id:              Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id:         Mapped[int]      = mapped_column(Integer, ForeignKey("users.id"), nullable=False, server_default="1")
    ts:              Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_now)

    # Values at snapshot time
    ngx_equity_ngn:  Mapped[float]   = mapped_column(Float, nullable=False, default=0.0)
    ngx_cost_ngn:    Mapped[float]   = mapped_column(Float, nullable=False, default=0.0)
    us_equity_usd:   Mapped[float]   = mapped_column(Float, nullable=False, default=0.0)
    us_cost_usd:     Mapped[float]   = mapped_column(Float, nullable=False, default=0.0)
    usdngn:          Mapped[float]   = mapped_column(Float, nullable=False, default=0.0)
    total_usd:       Mapped[float]   = mapped_column(Float, nullable=False, default=0.0)

    # Relationship to per-ticker prices
    prices: Mapped[list["PriceHistory"]] = relationship(
        "PriceHistory",
        back_populates="snapshot",
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        Index("ix_snapshots_ts",      "ts"),
        Index("ix_snapshots_user_ts", "user_id", "ts"),
    )


# ── price_history ─────────────────────────────────────────────────────────────

class PriceHistory(Base):
    """
    One row per ticker per snapshot.
    Powers per-stock price charts and sparklines.
    """
    __tablename__ = "price_history"

    id:          Mapped[int]   = mapped_column(Integer, primary_key=True, autoincrement=True)
    snapshot_id: Mapped[int]   = mapped_column(Integer, ForeignKey("portfolio_snapshots.id", ondelete="CASCADE"), nullable=False)
    ticker:      Mapped[str]   = mapped_column(String,  nullable=False)
    market:      Mapped[str]   = mapped_column(String,  nullable=False)
    price:       Mapped[float] = mapped_column(Float,   nullable=True)
    change_pct:  Mapped[float] = mapped_column(Float,   nullable=True)

    snapshot: Mapped["PortfolioSnapshot"] = relationship("PortfolioSnapshot", back_populates="prices")

    __table_args__ = (
        Index("ix_price_history_ticker_snapshot", "ticker", "snapshot_id"),
    )


# ── dividend_cache ─────────────────────────────────────────────────────────────

class DividendCache(Base):
    """Persistent L2 cache for dividend scrape results — one row per ticker."""
    __tablename__ = "dividend_cache"

    id:         Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker:     Mapped[str]      = mapped_column(String, nullable=False, unique=True)
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    symbol:     Mapped[str]      = mapped_column(String, nullable=False)
    currency:   Mapped[str]      = mapped_column(String, nullable=False, default="NGN")
    ex_dividend_date = mapped_column(String, nullable=True)
    record_date      = mapped_column(String, nullable=True)
    pay_date         = mapped_column(String, nullable=True)
    cash_amount      = mapped_column(Float,  nullable=True)   # None = "scraped but not found"
    dividend_ts      = mapped_column(String, nullable=True)

    __table_args__ = (
        Index("ix_dividend_cache_ticker", "ticker"),
    )


# ── financials_cache ───────────────────────────────────────────────────────────

class FinancialsCache(Base):
    """
    Persistent L2 cache for earnings history and balance sheet.
    cache_type is 'earnings' or 'balance'. List fields stored as JSON.
    """
    __tablename__ = "financials_cache"

    id:         Mapped[int]      = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker:     Mapped[str]      = mapped_column(String, nullable=False)
    cache_type: Mapped[str]      = mapped_column(String, nullable=False)   # 'earnings' | 'balance'
    fetched_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    periods    = mapped_column(JSON, nullable=False, default=list)   # list[str]
    col_a      = mapped_column(JSON, nullable=False, default=list)   # revenue | assets
    col_b      = mapped_column(JSON, nullable=False, default=list)   # eps     | liabilities
    col_c      = mapped_column(JSON, nullable=False, default=list)   # net_income | equity
    col_d      = mapped_column(JSON, nullable=True,  default=list)   # (unused for earnings) | net_cash

    __table_args__ = (
        UniqueConstraint("ticker", "cache_type", name="uq_financials_cache_ticker_type"),
        Index("ix_financials_cache_ticker_type", "ticker", "cache_type"),
    )


# ── daily_price_history ────────────────────────────────────────────────────────

class DailyPriceHistory(Base):
    """
    One row per ticker per calendar date.
    Populated by the /history/ page scraper (stockanalysis.com) with daily OHLCV data.
    Powers RSI, MA-50/200 and other technical indicators that need 200+ days.
    """
    __tablename__ = "daily_price_history"

    id:         Mapped[int]   = mapped_column(Integer, primary_key=True, autoincrement=True)
    ticker:     Mapped[str]   = mapped_column(String,  nullable=False)
    date:       Mapped[str]   = mapped_column(String,  nullable=False)   # ISO date YYYY-MM-DD
    close:      Mapped[float] = mapped_column(Float,   nullable=True)
    open:       Mapped[float] = mapped_column(Float,   nullable=True)
    high:       Mapped[float] = mapped_column(Float,   nullable=True)
    low:        Mapped[float] = mapped_column(Float,   nullable=True)
    volume:     Mapped[float] = mapped_column(Float,   nullable=True)
    change_pct: Mapped[float] = mapped_column(Float,   nullable=True)
    source:     Mapped[str]   = mapped_column(String,  nullable=False, default="history")

    __table_args__ = (
        UniqueConstraint("ticker", "date", name="uq_daily_price_history_ticker_date"),
        Index("ix_daily_price_history_ticker_date", "ticker", "date"),
    )


# ── watchlist ──────────────────────────────────────────────────────────────────

class Watchlist(Base):
    """Tickers a user wants to monitor but doesn't hold in their portfolio."""
    __tablename__ = "watchlist"

    id:          Mapped[int]            = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id:     Mapped[int]            = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    ticker:      Mapped[str]            = mapped_column(String,  nullable=False)
    market:      Mapped[str]            = mapped_column(String,  nullable=False, default="NGX")
    added_at:    Mapped[datetime]       = mapped_column(DateTime(timezone=True), default=_now, nullable=False)
    added_price: Mapped[float]           = mapped_column(Float, nullable=True)

    __table_args__ = (
        UniqueConstraint("user_id", "ticker", name="uq_watchlist_user_ticker"),
        Index("ix_watchlist_user_id", "user_id"),
    )